from __future__ import annotations

from typing import Dict, List

import requests


def query_llm(
    messages: List[Dict[str, str]],
    base_url: str,
    model: str,
    max_tokens: int = 2048,
    temperature: float = 0.2,
    timeout: int = 180,
) -> str:
    url = f"{base_url.rstrip('/')}/chat/completions"
    payload = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": temperature,
        "stream": False,
    }
    try:
        response = requests.post(url, json=payload, timeout=timeout)
        response.raise_for_status()
        data = response.json()
        message = data["choices"][0]["message"]

        # Thinking modelleri (Gemma 4 vb.) cevabı content yerine
        # reasoning_content'e yazar. İkisine de bak.
        content = message.get("content", "")
        if not content:
            # Thinking modeli — reasoning_content'ten son bölümü al
            reasoning = message.get("reasoning_content", "")
            if reasoning:
                # Drafting/Summary bölümünü bul, oradan itibaren al
                markers = ["**Summary", "**(1)", "## Summary", "Draft", "draft"]
                cut = -1
                for marker in markers:
                    idx = reasoning.rfind(marker)
                    if idx != -1 and idx > cut:
                        cut = idx
                content = reasoning[cut:] if cut != -1 else reasoning[-1500:]

        return content.strip() if content else "No response generated by LLM."
    except requests.exceptions.Timeout:
        return f"LLM request timed out after {timeout}s. Please ensure LM Studio is running."
    except requests.exceptions.RequestException as e:
        return f"LLM unavailable: {e}. Please ensure LM Studio is running on {base_url}."
    except (KeyError, IndexError) as e:
        return f"Unexpected LLM response format: {e}"


def check_llm_health(base_url: str, timeout: int = 5) -> bool:
    url = f"{base_url.rstrip('/')}/models"
    try:
        response = requests.get(url, timeout=timeout)
        return response.status_code == 200
    except requests.exceptions.RequestException:
        return False